### PR TITLE
Mobile menu

### PR DESCRIPTION
**Pull request by GOlivierNation**
**What is Done on this branch:**
***********************************
- For this project, I added the [JavaScript + HTML + CSS linter].

- [x] In mobile, implement the following features:

- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

### CODE REVIEW

**Review by OLIPLICHE — CHANGES_REQUESTED** [review]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
 Linter result is green ✔️
 Commit messages are meaningful✔️
 The pull request have a descriptive title telling you what changes are inside ✔️
 The pull request have a short summary describing introduced changes in more detail ✔️
 node_modules folder is in the .gitignore ✔️

## Required Changes ♻️

- [x] Please your app is not working properly: When I click the hamburger button, the mobile menu appears and disappears alone within a second. 
- [x] Kindly make sure that when the mobile menu appears, it must be stable so that you can check all the features based on the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md).  

e1



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Lordkaito — CHANGES_REQUESTED** [review]
Hi @GOlivierNation, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] As mentioned by the previous reviewer, your mobile menu is not working as expected. Right now, when you click for the first time on the menu icon, the menu appears and disappears automatically within one second. Then, you cannot open the menu again after some time. Please work on this issue as this is part of the requirements for this milestone.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by GOlivierNation** [comment]
Hello @OLIPLICHE @Lordkaito  I can't see the issue you are talking about once I inspect my codes to mobile view, is there anyone to let me know if we can have a call to check on this?

**Comment by Lordkaito** [comment]
> Hello @OLIPLICHE @Lordkaito I can't see the issue you are talking about once I inspect my codes to mobile view, is there anyone to let me know if we can have a call to check on this?

I am wondering if the issue has something to see with your `setActive` function. Even though it should not, I am not sure. If you cannot find the issue, I can jump on a call with you tomorrow.

**Comment by GOlivierNation** [comment]
> `setActive`

Okay, thank you @Lordkaito Maybe tomorrow we can have a call and let me see because I can't see that issue on my end.

**Comment by GOlivierNation** [comment]
Hello, @OLIPLICHE @Lordkaito  you can check now I have changed everything.

**Review by nicupop729 — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 

Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
